medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: "{{ env_var('POSTGRES_USER', 'postgres') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'password') }}"
      port: 5432
      dbname: "{{ env_var('POSTGRES_DB', 'medical_warehouse') }}"
      schema: dbt_dev
      threads: 1
    prod:
      type: postgres
      host: localhost
      user: "{{ env_var('POSTGRES_USER', 'postgres') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'password') }}"
      port: 5432
      dbname: "{{ env_var('POSTGRES_DB', 'medical_warehouse') }}"
      schema: dbt_prod
      threads: 4
